### ISSUE TITLE
First request of spider doesn't use configured User-Agent

### ISSUE THREAD

**Issue by cstrouse** [benjaminestes/crawl#31]
The first request made during the crawl uses the default User-Agent set in `net/http` which is `Go-http-client/1.1`. If the user has configured a desired User-Agent value it should be used for all requests including the sitemap fetch.

**Comment by benjaminestes** [comment]
@cstrouse Can you confirm that you're seeing this for requests for robots.txt files? Or alternatively give further details on reproducing? I've traced through the code and it looks like it's the `addRobots` method that doesn't use the correct User-Agent, regardless of whether that's the first request.

**Comment by benjaminestes** [comment]
dec5662 is my first attempt to fix—let me know if problem persists.

**Comment by cstrouse** [comment]
It's showing the right User-Agent now for all requests.
